### ISSUE TITLE
"Enable access for assistive devices" gone in 10.9 Mavericks

### ISSUE THREAD

**Issue by zhigang1992** [ryanolsonk/LLDB-QuickLook#3]
But I found this,
http://www.tekrevue.com/2013/06/25/how-to-enable-access-for-assistive-devices-in-os-x-mavericks/

**Comment by ryanolsonk** [comment]
Thanks for the heads up. I'm still unsure of the best approach here since this is not a full app but just a script. Using AppleScript to open quicklook is pretty hacky in the first place - I wish there was a way to invoke the full version from the command line.

**Comment by ryanolsonk** [comment]
This is working for me without having to toggle any settings on Mavericks. I'm going to make a note in the readme and close this issue. Let me know if see any issues using the tool on Mavericks.
